spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testsec?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: DemoService

application:
  security:
    jwt:
      secret-key: 743777217A25432A462D4A614E635266556A586E3272357538782F413F442847
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 8088

bezkoder:
  openapi:
    dev-url: http://localhost:8088
    prod-url: https://localhost:8080

logging:
    level:
        org:
        springframework:
            security: DEBUG
            web: DEBUG
            data: DEBUG
            hibernate: DEBUG
            jpa: DEBUG
            sql: DEBUG
            jwt: DEBUG
            bezkoder: DEBUG
